apiVersion: apps/v1
kind: Deployment
metadata:
  name: spencers-backend
  labels:
    app: spencers-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spencers-backend
  template:
    metadata:
      labels:
        app: spencers-backend
    spec:
      containers:
      - name: backend
        image: spencers/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: spencers-backend
spec:
  selector:
    app: spencers-backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
